name: Build and deploy
run-name: Building and deploying static assets
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - run: make up
      - run: make gen
