name: Build and deploy
run-name: Building and deploying static assets
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@main
      - name: build ssg src
        run: make up
      - name: generate static assets
        run: make gen
      - name: list static assets
        run: tree
